### ISSUE TITLE
Rebuild driver for 17.01.4?

### ISSUE THREAD

**Issue by BrushXue** [eduperez/mwlwifi_LEDE#10]
Any plans to release the binary for the new system?
Or can I force install the package for 17.01.3? Since it's really urgent to fix KRACK.

**Comment by eduperez** [comment]
What? Has 17.01.4 been released? Did I miss the announcement?

**Comment by ghost** [comment]
I don't know why or how but 17.01.4 was released today .... wtf?

https://downloads.lede-project.org/releases/

**Comment by eduperez** [comment]
I have just seen the announcement... you guys are fast!

I am building the driver right now, but it will not be ready until tomorrow, and I will not be able to test it myself for a couple of days more.

**Comment by eduperez** [comment]
Driver released at https://github.com/eduperez/mwlwifi_LEDE/releases/tag/e119077
