### ISSUE TITLE
Fatal address complications

### ISSUE THREAD

**Issue by eddievhfan1984** [eduperez/mwlwifi_LEDE#17]
I just installed the latest release onto my WRT1900ACv2 running OpenWRT 18.06 release (both kmod and firmware packages), and when I reboot the router to let it all take effect, I find that my connection gets seriously borked—while certain common sites like Google and Facebook are accessible, I can't SSH or use LuCI to get back into the router, with an "ADDRESS UNREACHABLE" error thrown. (I can't even access GitHub that way). IDK if this is repeatable, but I was only able to recover from this on account of using extroot and unplugging my overlay USB flash drive to reset everything.

**Comment by eduperez** [comment]
This does not seem to be related to the mwlwifi drivers at all. If it fails, it should fail for all sites, not only some of them. If you can reach any external site, there is a working connection with the router. I think you should try to find out what is happening.
