### ISSUE TITLE
Support for openwrt 19.07

### ISSUE THREAD

**Issue by imwhocodes** [eduperez/mwlwifi_LEDE#21]
Hi, I upgraded to openwrt 19.07 but the default mwlwifi firmware is not working, the 5Ghz is completely broken

There is any release here on pipeline?

Thanks

**Comment by eduperez** [comment]
Release 19.07.0 already contains the latest version of these drivers, I am afraid there aren't any news around here.

On the other hand, it is working for me, perhaps the issue is specific to your configuration. I would post a comment on the forum.

**Comment by exaudio** [comment]
@imwhocodes , I'm running OpenWRT 19.07.1 on my WRT3200ACM with @eduperez's [builds] (https://github.com/eduperez/mwlwifi_LEDE/releases/tag/a2fd00b) of the latest mwlwifi commits that include newer firmware than the stock 19.07.1 release. My router has been up for a week now and I haven't had any issues with 5Ghz or anything else for that matter.

**Comment by greg45416** [comment]
I have also been using 19.07.1 with a2fd00b, and it works for me, too.   It looks like a2fd00b isn't in the soon-to-be-released 19.07.2, but maybe it can get pulled into the branch in time for 19.07.3?

Eduperez - Thanks for your ongoing work on this!  I've been using your firmware updates since the LEDE days when there were frequent drops of the firmware coming from Marvell wireless.

Edit: I should have mentioned that I'm running on WRT3200ACM hardware, and wifi worked for me both with the stock 19.07.1 firmware and with the a2fd00b update from Eduperez.

**Comment by yangxq** [comment]
I upgraded to  19.07.1 and the 5G is broken.  Then I installed 10.3.8.0-20181210-a2fd00b and it shows "device not activated". Then I modified the /etc/config/wireless, Change the "option htmode 'VHT80'" to "option htmode 'VHT40'". After reboot, the 5G is ok finally.

My device is wrt1900ac.

**Comment by huntergregal** [comment]
What about support for for kernel 4.14.171 ?

**Comment by blitmap** [comment]
@huntergregal:

```
root@someBox:/lib/modules/4.14.171# ls -al mwlwifi.ko
lrwxrwxrwx    1 root     root            22 May 17 06:18 mwlwifi.ko -> ../4.14.167/mwlwifi.ko
```

Just do: `ln -s /lib/modules/4.14.167/mwlwifi.ko /lib/modules/4.14.171`

The module loads fine (I believe because it doesn't break the minor kernel version (4.**14**)

**Comment by Toetje585** [comment]
I downloaded 19.07.03, then removed the included wifi drivers and replaced them with the latest hereo n this github.

kmod-mwlwifi_4.14.180+thagabe-93c3d8d1-1_arm_cortex-a9_vfpv3-d16
mwlwifi-firmware-88w8864_thagabe-93c3d8d1-1_arm_cortex-a9_vfpv3-d16

WRT1900acs V2

Wifi is not working, interface not starting and if it start it only starts at a reboot. then after while it crashes again. and dmesg is not telling me anything :)

**Comment by biodigitalfish** [comment]
@Toetje585 i think you only need to install the second one mwlwifi-firmware..

If that doesn’t work suggest:
* restore / reinstall from snapshot
* from shell type: wifi down
* uninstall existing driver
* install the new one.

Has worked for me in the past.

**Comment by Toetje585** [comment]
> @Toetje585 i think you only need to install the second one mwlwifi-firmware..
> 
> If that doesn’t work suggest:
> 
> * restore / reinstall from snapshot
> * from shell type: wifi down
> * uninstall existing driver
> * install the new one.
> 
> Has worked for me in the past.

KMOD should be the driver and the mlwifi the firmware as far as I know :)

**Comment by biodigitalfish** [comment]
@eduperez - Getting the same issue with WRT1900acs as @Toetje585 using the latest build: "kmod-mwlwifi - 4.14.180+thagabe-93c3d8d1-1".

Have tried reflashing to start fresh. But interfaces refusing to come up. Can't see anything useful.
Downgrading to 10.3.8.0-20181210 for 19.07.3 has got it going again.

Looking at the upstream feedback, looks like some people are saying its working good for the WRT3200. Probably need to split out this change to just be for 3200 perhaps

**Comment by eduperez** [comment]
@thagabe seems to have decided his modifications were not interesting any longer, and has deleted his repo; there will be no more "thagabe" packages.
