### ISSUE TITLE
Missing or incorrectly named kmod driver for 19.07.5

### ISSUE THREAD

**Issue by BlowflyOZ** [eduperez/mwlwifi_LEDE#22]
Hi,

I'm trying to update my wrt1900acs running 19.07.5 kernel 4.14.209 but I think there's a file missing or something not quite right with the versions offered. .

Please see in the precompiled assets listed for OWRT version 19.07.5. -  It seems one listed ipk file is missing for download. 

kmod-mwlwifi_4.14.209+thagabe-93c3d8d1-19074_arm_cortex-a9_vfpv3-d16.ipk, although listed as correct for my version of hw/sw, this precompiled file does not actually exist.

I've tried kmod-mwlwifi_4.14.209+thagabe-93c3d8d1-19075_arm_cortex-a9_vfpv3-d16.ipk but I'm getting dependency errors.

Please can you confirm/provide the correct firmware/kmod files for 19.07.5

thanks

**Comment by BlowflyOZ** [comment]
also, forgot to mention that my 19.07.5 release build kernel version is 4.14.209-1-a92a3f5c5bed2671533484c7ace9d5b5 whereas the precompiled kmod-mwlwifi_4.14.209+thagabe-93c3d8d1-19075_arm_cortex-a9_vfpv3-d16.ipk file (which is possibly the intended driver update for 19.07.5?) has been compiled against a different kernel  or 4.14.209-1-fe7f5134e891244a2d03219b1fc96517

I'm trying to figure whats gone wrong here. thanks for your help!

**Comment by xthezealot** [comment]
In the meantime, you can force the install:

```sh
opkg install --force-reinstall --nodeps kmod-mwlwifi_4.14.209\+thagabe-93c3d8d1-19075_arm_cortex-a9_vfpv3-d16.ipk
```

**Comment by eduperez** [comment]
The names on some packages for 19.07.5 where wrong, and used "19074" instead of "19075", but the issue was just on the description; I have fixed that. Other users have also pointed out the dependency issue; I am rebuilding the packages right now, and hope that will fix this, too.

**Comment by BlowflyOZ** [comment]
Thanks for taking a look. 

FYI I just tested on a separate wrt32x router.

It seems the issue is the same for both wrt1900acs and wrt32x/wrt32ACM files. On wrt32x the firmware installs ok but the 1705 kmod driver again reports an incorrect non standard release kernel version as well, same as before :  fe7f5134e891244a2d03219b1fc96517

just thought I'd let you know!

**Comment by eduperez** [comment]
I have uploaded again the packages for 19.07.5, hope this fixes the dependencies iisue.
