### ISSUE TITLE
Asset missing for 19.07.5

### ISSUE THREAD

**Issue by leocrawford** [eduperez/mwlwifi_LEDE#23]
`kmod-mwlwifi_4.14.209+thagabe-93c3d8d1-19075_arm_cortex-a9_vfpv3-d16.ipk` appears to be misisng

**Comment by eduperez** [comment]
Yes, the files were corrupt, and I had to take them down. I will create new packages as soon as possible. Thanks

**Comment by eduperez** [comment]
@thagabe seems to have decided his modifications were not interesting any longer, and has deleted his repo; there will be no more "thagabe" packages.

**Comment by leocrawford** [comment]
Thanks for responding, shame about the repo. What are the implications of that? Does that mean no more binaries?

**Comment by eduperez** [comment]
There will be new binaries as soon as someone shares any code worth packaging. Stable OpenWrt releases already ship latest official drivers from the official repo.

**Comment by leocrawford** [comment]
Openwrt doesn't seem to be running latest as v19.07.5 gives:

opkg list_installed | grep mwlwifi
kmod-mwlwifi - 4.14.209+2019-03-02-31d93860-1
mwlwifi-firmware-88w8964 - 2019-03-02-31d93860-1

driver version: 10.3.8.0-20181210
firmware version: 0x09030206

Whereas latest firmware seems to be 9.3.2.12
<https://github.com/kaloz/mwlwifi/commit/b0aeee507f1534ae40fab9d2420a6319e1f33de5>
(and
has been for 11 months).

Leo

**Comment by eduperez** [comment]
Ok, I can create packages for the latest firmware at @kaloz's repo.
