### ISSUE TITLE
Can't install on OpenWrt Insomnia 19.07.6

### ISSUE THREAD

**Issue by mgscreativa** [eduperez/mwlwifi_LEDE#24]
Hi! Trying to install the package I get:
```
root@OpenWrt:/tmp# opkg install --force-downgrade kmod-mwlwifi_4.14.180\+thagabe-93c3d8d1-19073_arm_cortex-a9_vfpv3-d16.ipk 
Downgrading kmod-mwlwifi on root from 4.14.215+2019-03-02-31d93860-1 to 4.14.180+thagabe-93c3d8d1-19073...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-mwlwifi:
 * 	kernel (= 4.14.180-1-a92a3f5c5bed2671533484c7ace9d5b5)
 * opkg_install_cmd: Cannot install package kmod-mwlwifi.
```
Any chance to get this fixed? I downloaded the latest release available here.

Thanks  a lot!

**Comment by eduperez** [comment]
You are trying to install packages intended for 19.07.**3** on top of 19.07.**6**... that is not going to work.
The "_thagabe_" series of patches was abandoned by the author, as they caused trouble without any noticeable gains.
You can install from tag "`a2fd00b`", but you must install the "`kmod-mwlwifi`" and "`mlwifi-firmware`" packages together; and only if you own a WRT3200ACM or WRT32X, as the firmware for the other routers is exactly the same as stock 19.07.6.

**Comment by mgscreativa** [comment]
Hi @eduperez !

I have WRT3200ACM
I was able to install mwlwifi-firmware-88w8964_kaloz-a2fd00bb-19076_arm_cortex-a9_vfpv3-d16.ipk, but installing kmod-mwlwifi_4.14.215+kaloz-a2fd00bb-19076_arm_cortex-a9_vfpv3-d16.ipk I got
```
root@OpenWrt:/tmp# opkg install --force-downgrade kmod-mwlwifi_4.14.215\+kaloz-a2fd00bb-19076_arm_cortex-a9_vfpv3-d16.
ipk 
Upgrading kmod-mwlwifi on root from 4.14.215+2019-03-02-31d93860-1 to 4.14.215+kaloz-a2fd00bb-19076...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-mwlwifi:
 * 	kernel (= 4.14.215-1-a92a3f5c5bed2671533484c7ace9d5b5)
 * opkg_install_cmd: Cannot install package kmod-mwlwifi.
```

I'm using `OpenWrt 19.07.6 insomnia r11278-8055e38794`

**Comment by eduperez** [comment]
"OpenWrr 19.07.6 insomnia" is not the same as "OpenWrt 19.07.6"...

To install these packages, you need an official OpenWrt release, not a build made by someone else.

**Comment by mgscreativa** [comment]
Cool! Thanks a lot!

**Comment by mgscreativa** [comment]
Hi @eduperez just wondering, since I can't get to install the kmod package, ¿is it possible for me to compile your drivers source directly on the router? Any chance you can guide me? Thanks!

**Comment by eduperez** [comment]
No, I am afraid that you cannot compile the drivers on the router, you need to set up a building environment on your computer:

* https://openwrt.org/docs/guide-user/additional-software/beginners-build-guide
* https://openwrt.org/docs/guide-user/additional-software/imagebuilder
* https://openwrt.org/docs/guide-developer/quickstart-build-images

However, you need to download the sources and build options from "insomnia", instead of the official repo.

**Comment by mgscreativa** [comment]
Thanks a lot!

I got help from the insomnia maintainer anyway

```
cd /lib/firmware/mwlwifi
mv 88W8964.bin 88W8964.bin.ORG
wget https://github.com/kaloz/mwlwifi/raw/master/bin/firmware/88W8964.bin -O 88W8964.bin.OEM
ln -s 88W8964.bin.OEM 88W8964.bin
reboot
```

I'ts the same as your packages rigth?

**Comment by eduperez** [comment]
I do not remember exactly what changes on each version, but it is quite probable that this version only changed the binary firmware. So, yes, that should be enough.
